### ISSUE TITLE
Out of bounds heap read in VC2Decoder::parseSeqHeader / read_uint / read_bool

### ISSUE THREAD

**Issue by hannob** [bbc/vc2hqdecode#14]
The attached file will trigger an out of bounds heap read in vc2decode. To see this you need to compile it with a memory safety tool like address sanitizer (-fsanitize=address in compile flags).

[vc2decode-heap-oob-parseSeqHeader.zip](https://github.com/bbc/vc2hqdecode/files/1168311/vc2decode-heap-oob-parseSeqHeader.zip)

Here's the stack trace from asan:
```
==8442==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000ef1d at pc 0x55cca65a5a65 bp 0x7ffda97f29e0 sp 0x7ffda97f29d0
READ of size 1 at 0x60200000ef1d thread T0
    #0 0x55cca65a5a64 in read_bool(unsigned char*&, int&, unsigned char const*) /f/vc2/vc2hqdecode/vc2hqdecode/vlc.hpp:55
    #1 0x55cca65a5a64 in read_uint(unsigned char*&, int&, unsigned char const*) /f/vc2/vc2hqdecode/vc2hqdecode/vlc.hpp:80
    #2 0x55cca65a5a64 in VC2Decoder::parseSeqHeader(char*, char const*) /f/vc2/vc2hqdecode/vc2hqdecode/VC2Decoder.cpp:453
    #3 0x55cca65a6384 in VC2Decoder::sequenceSynchronise(char**, int, bool) /f/vc2/vc2hqdecode/vc2hqdecode/VC2Decoder.cpp:190
    #4 0x55cca658cc08 in vc2decode_synchronise /f/vc2/vc2hqdecode/vc2hqdecode/vc2hqdecode.cpp:109
    #5 0x55cca654582b in main /f/vc2/vc2hqdecode/testprogs/vc2decode.cpp:250
    #6 0x7f337dafe1d0 in __libc_start_main (/lib64/libc.so.6+0x201d0)
    #7 0x55cca654afc9 in _start (/r/vc2/vc2decode+0x15fc9)

0x60200000ef1d is located 0 bytes to the right of 13-byte region [0x60200000ef10,0x60200000ef1d)
allocated by thread T0 here:
    #0 0x7f337ea6c640 in malloc (/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/libasan.so.3+0xc7640)
    #1 0x55cca6544f9c in main /f/vc2/vc2hqdecode/testprogs/vc2decode.cpp:202
    #2 0x7f337dafe1d0 in __libc_start_main (/lib64/libc.so.6+0x201d0)

**Comment by jamesba** [comment]
Fixed now.
