### ISSUE TITLE
Infinite loop when decoding possible bad data

### ISSUE THREAD

**Issue by JDarnley** [bbc/vc2hqdecode#15]
I encountered an infinite loop while attempting to decode decoding a stream of our own encoder.  I am not saying that the bitstream is correct and that I expect to get a picture from vc2hqdecode but an infinite loop is not good behavior.

Arch Linux, x86-64, kernel 4.9.78-1, Boost 1.66.0-1, gcc 7.2.1+20180116-1

gdb backtrace when I hit Ctrl+C
```
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./testprogs/vc2decode...done.
(gdb) r
Starting program: /home/james/src/vc2hqdecode/testprogs/vc2decode /home/james/dirac-vc2-samples/1080i25.vc2 /dev/null
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
INFO: Processor Features:
INFO:   SSE4.2 [ ]
INFO:   AVX    [ ]
INFO:   AVX2   [ ]
Read 2025172bytes of input data
INFO: Processing Sequence Header
INFO: Configuring for 1920 x 1080
INFO: Processing Transform Params
INFO: Configuring for 1 threads, 4 jobs
^C
Program received signal SIGINT, Interrupt.
decode_c (olength=128, odata=0x55555583f240, ilength=44,
    idata=0x7ffff6c0c93c 'S' <repeats 32 times>, '\377' <repeats 12 times>, "\006", 'S' <repeats 16 times>, "\377\377\377\377\377\377\377\377\006", 'S' <repeats 16 times>, "\377\377\377\377\377\377\377\377") at vlc_c.cpp:120
120         odata[ocounter + 4] = E.val4;
(gdb) bt
#0  decode_c (olength=128, odata=0x55555583f240, ilength=44,
    idata=0x7ffff6c0c93c 'S' <repeats 32 times>, '\377' <repeats 12 times>, "\006", 'S' <repeats 16 times>, "\377\377\377\377\377\377\377\377\006", 'S' <repeats 16 times>, "\377\377\377\377\377\377\377\377") at vlc_c.cpp:120
#1  decode_slices_c<short> (matrices=0x55555583f790, input=<optimized out>, scratch=0x555555826608, n_slices_x=<optimized out>, n_slices_y=68, video_data=0x555555826620, slice_width=32,
    slice_height=4, depth=1, dequant=0x5555557da550) at vlc_c.cpp:196
#2  0x00005555555795a5 in VC2Decoder::Decode (_ostride=0x7fffffffe610, _odata=0x5555557d9ef0, job=0x555555826600, this=0x5555557da320) at VC2Decoder.cpp:1455
#3  VC2Decoder::handleFragment (this=this@entry=0x5555557da320, _idata=_idata@entry=0x7ffff6c162fd "", ilength=ilength@entry=1012711, odata=odata@entry=0x5555557d9ef0,
    ostride=ostride@entry=0x7fffffffe610) at VC2Decoder.cpp:1105
#4  0x000055555557c00e in VC2Decoder::sequenceDecodeOnePicture (this=0x5555557da320, _idata=0x7fffffffdef8, ilength=2025154, odata=0x5555557d9ef0, ostride=0x7fffffffe610, skip_aux=true)
    at VC2Decoder.cpp:280
#5  0x000055555556c904 in vc2decode_decode_one_picture (handle=<optimized out>, idata=<optimized out>, ilength=<optimized out>, odata=<optimized out>, ostride=<optimized out>,
    skip_aux=<optimized out>) at vc2hqdecode.cpp:117
#6  0x000055555555b02b in main (argc=<optimized out>, argv=<optimized out>) at vc2decode.cpp:309
```

~I will consider where I can put the sample to be able to share with you.~
Sample is available here: https://0x0.st/sTsw.vc2

**Comment by jamesba** [comment]
Fixed.

This was an bug in the test program, which would exit from the main runloop if no *pictures* had been decoded from a file or when the expected number of *frames* had been decoded. A file containing pictures but no complete frames caused an infinite loop.
